### ISSUE TITLE
Suraj's Trial Week Completion

### ISSUE THREAD

**Issue by surajsharma** [holdex/holdex-venture-studio#328]
I really enjoyed working at Holdex during my trial week, here's a summary of issues i helped with:

## Issues Discovered

- [ ] [1.Problem: hamburger menu not toggling in development (Chrome/Firefox) #301](https://github.com/holdex/holdex-venture-studio/issues/301)

- [x] [2. Problem: Links on home page are relative #299](https://github.com/holdex/holdex-venture-studio/issues/299)

- [ ] [3. Problem: rubberband scrolling reveals unstyled background #297](https://github.com/holdex/holdex-venture-studio/issues/297)
  

### ✅ 1. italic in quote component breaks horizontal rhythm

- [goal:226](https://github.com/holdex/holdex-venture-studio/issues/226)

- [x] issue: https://github.com/holdex/holdex-venture-studio/issues/110

- [x] pr1: https://github.com/holdex/holdex-venture-studio/pull/294

- time: 30 mins

- [x] pr2: https://github.com/holdex/holdex-venture-studio/pull/295

- time: 30 mins

---

### ✅  2. Missing target="_blank" on some links 

- [goal:226](https://github.com/holdex/holdex-venture-studio/issues/226)

- [x] issue: https://github.com/holdex/holdex-venture-studio/issues/67

- [x] pr: https://github.com/holdex/holdex-venture-studio/issues/67

- time: 30 mins

---

### ✅  3. Problem: links in table are buggy

- [goal:226](https://github.com/holdex/holdex-venture-studio/issues/226)

- [x] issue: https://github.com/holdex/holdex-venture-studio/issues/159

- [x] pr1: https://github.com/holdex/holdex-venture-studio/pull/303

- [x] pr2: https://github.com/holdex/holdex-venture-studio/pull/310

- time taken: 5 hours

---

### ✅ 4.  Problem: ticker underline is not by design 

- [goal:226](https://github.com/holdex/holdex-venture-studio/issues/226)

- [x] issue: https://github.com/holdex/holdex-venture-studio/issues/99

- [x] pr: https://github.com/holdex/holdex-venture-studio/pull/308

- time: 20 mins

---

### 5. Problem: twitter tweets has disappeared from threads

- [goal:226](https://github.com/holdex/holdex-venture-studio/issues/226)

- [x] issue: https://github.com/holdex/holdex-venture-studio/issues/60

- [ ] pr: https://github.com/holdex/holdex-venture-studio/pull/317

- pending / awaiting review

- time: 6 hours

---

- [all tasks assigned](https://github.com/holdex/holdex-venture-studio/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+assignee%3Asurajsharma
)
- [all issues started](https://github.com/holdex/holdex-venture-studio/issues/created_by/surajsharma)
