### ISSUE TITLE
Problem: Discord community is not set up

### ISSUE THREAD

**Issue by markholdex** [holdex/holdex-venture-studio#439]
```[tasklist]
### Tasks
- [x] Create a model of the community naivgation in FigJam (include roles and what they can see)
- [x] Read only channel with quick access to our Principles and guides
- [x] Team announcements channel (for team members only)
- [x] Blog channel
- [x] Trial, trial Q&A and other trial related documentation
- [x] Off-topic channel
- [x] Per Project channels
- [x] Public for all Channel with jobs and instructions on how to apply
- [x] Welcome channel with basic behavior guides (source inspiration from other Discord communities)
- [x] A channel for team members to share accomplishments, life events and stuff like that
- [x] Team members chat
- [x] HR channel/s
- [x] Add Discord to Holdex website soci
- [x] Add Discord into the headhunting funnel process
- [x] Populate channels with content
```

## [FigJam](https://www.figma.com/file/CFvlzLGS98qhLysiDKpkba/Discord-Community?type=whiteboard&node-id=0%3A1&t=KnmmzbZcWtvx36XI-1)

**Comment by zolotokrylin** [comment]
@predrag-us I left comments in figma

**Comment by predrag-us** [comment]
@zolotokrylin 

Can you please remove the `partnerships` and `contributors` roles on Discord? 

<img width="637" alt="CleanShot 2023-07-05 at 12 17 03@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/21cf141e-e4d8-4197-93ba-49386e3046d5">

--- 

Log: Mark and I had a meeting on what we're going to cover in the initial version of Discord.

**Comment by zolotokrylin** [comment]
> Mark and I had a meeting on what we're going to cover in the initial version of Discord.

1. What are you going to cover? please leave the log of the agreed scope
2. `partnerships` was removed
3. Can we call `moderator` as `maintainer`. This is how in software those who maintain repos/organisations in github are called https://docs.github.com/en/organizations/organizing-members-into-teams/assigning-the-team-maintainer-role-to-a-team-member. It fits better our nature of the business. Also, these roles need to correspond to the relevant github repos

**Comment by predrag-us** [comment]
@zolotokrylin 

1. We agreed that we're not going to make Discord our communication channel but only use it for marketing purposes for the time being. Therefore, we'll have just a portion of categories and channels compared to the initial proposal ⏤ and you can see them since they're already prepared.
3. Sure.

**Comment by zolotokrylin** [comment]
> removing contributors

done

**Comment by zolotokrylin** [comment]
What's the ETA here and what's missing?

**Comment by predrag-us** [comment]
ETA: ~1 hour.
I just have to check the `contributors` role, everything else is ready.

**Comment by zolotokrylin** [comment]
I have added a few checklist items in the description

**Comment by predrag-us** [comment]
Log: Discord has been set up and Discord has been added to the website Navigation and Footer. 

There's one more task left ⏤ `Add Discord into the headhunting funnel process` ⏤ @almon-s can you help with this one? I'm guessing it's concerning you since it's about headhunting.

**Comment by predrag-us** [comment]
Log: Discord channels have been populated with introduction content. We'll need some concrete content for #trial-qa, since I don't have questions and answers.

@almon-s maybe you can help me with this? Please confirm, assign yourself, and let me know once you have the content so I can update the Discord. Thank you!

**Comment by almon-s** [comment]
@predrag-us yes, can i get an invite to the discord channel aswell thanks. If you need me to help with anything I can do it

> We'll need some concrete content for #trial-qa, since I don't have questions and answers.

Do you mean this? [Trial FAQ](https://holdex.io/c/learn/trial-period-faq) or are you looking for something more?

**Comment by predrag-us** [comment]
@zolotokrylin @markholdex 

The Discord has been set up ⏤ please review.
If everything is okay, we can add Discord to website, #447.

--- 

@zolotokrylin 

Please check Almon's comment above. 

> @zolotokrylin updated our [headhunting funnel](https://docs.google.com/document/d/1oUObqYvGix6--GMwCTU_iQ-JQv0UQQx6Gx3t842fqs8/edit), please have a look. Made some relevant edits too based on our call.

**Comment by zolotokrylin** [comment]
@predrag-us I trust you here. I am limited with time to check everything. Please proceed with adding to the website.

**Comment by markholdex** [comment]
@predrag-us discord was ready when you complete it. Good job with that 🔥  Don't be afraid to mark tasks as completed once you complete them. If we will notice something later on, we will report a new problem. ✌️
