### ISSUE TITLE
Problem: The table isn't implemented by the design

### ISSUE THREAD

**Issue by predrag-us** [holdex/holdex-venture-studio#478]
Problem: The table isn't implemented by the design

_Originally posted by @predrag-us in https://github.com/holdex/holdex-venture-studio/issues/477#issuecomment-1657954295_

---

### [Figma Design](https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=1475%3A12342&mode=design&t=P0MRBF15SvF4PmSF-1)

```[tasklist]
### Tasks
- [x] Check the `font-size` (should be 14px instead of 18px)
- [x] Check the `<th>` `font-weight` (should be bold instead of regular)
- [x] Check the `<th>` alignment (should be left instead of centered)
- [x] Check the `<td>` text `color`
- [x] Check the cell content alignment (should be top-left instead of centered)
- [x] The table doesn't span full-width | [second one](https://holdex.io/c/learn/crypto-and-web3-events)
- [x] The table width on large screens is inaccurate (should be 710px instead of 604px). I even noticed a table with 655.22px which shouldn't be the case. Our dimensions are 710px and 604px | [first one](https://holdex.io/c/learn/crypto-and-web3-events)
- [x] We should have a `max-width` for the columns. My recommendation is 200px. So, when we have a longer text, don't try to squeeze it in (for example, available space) 100px but allow it to span the full 200px
- [x] The tables should be scrollable on the x-axis while the first column should be fixed. Notice the fades in the design, after the first column and after the last column, indicating there's more on the left and right. So, don't try to squeeze everything in 710px, but allow scrolling on the x-axis while the column `max-width` is 200px and the first column has a fixed position
- [x] Please have another look yourself, since I may have missed something. Check this item after you've done your own inspection
```

---

An example of how the table should look like:

<img width="954" alt="CleanShot 2023-07-31 at 11 43 27@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/24b26628-b1a7-4380-a012-e64cc410fcfe">

Compared to now:

<img width="638" alt="CleanShot 2023-07-31 at 11 40 13@2x" src="https://github.com/holdex/holdex-venture-studio/assets/18451941/3b8bf5b7-a32c-48a6-8d05-1019196b39b9">

**Comment by misagfo** [comment]
![image](https://github.com/holdex/holdex-venture-studio/assets/21268553/c5664f3d-1908-4007-aef5-920a9bf543fc)


The table has 710 pixel it is impossible to put all the text like in the picture

**Comment by predrag-us** [comment]
@misagfo Please read the description. It's not meant to fit in one view, because it's impossible as you said. We have to implement a scrolling table.

**Comment by misagfo** [comment]
Ah OK, 
![image](https://github.com/holdex/holdex-venture-studio/assets/21268553/5efc20b5-c2e6-49f1-ac50-36df5e8a5b33)
this column should be fixed correctly?

**Comment by predrag-us** [comment]
@misagfo That’s correct.

**Comment by zolotokrylin** [comment]
@georgeciubotaru it is even worse now! 
<img width="996" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/884a7d20-8dc5-49da-8646-d4a00a1a2cef">

**Comment by surajsharma** [comment]
> @georgeciubotaru it is even worse now! <img alt="image" width="996" src="https://user-images.githubusercontent.com/1125014/266519053-884a7d20-8dc5-49da-8646-d4a00a1a2cef.png">

this is an edge case where the content isn't fittable on either of the two table sizes fixed by design.

**Comment by surajsharma** [comment]
> > @georgeciubotaru it is even worse now! <img alt="image" width="996" src="https://user-images.githubusercontent.com/1125014/266519053-884a7d20-8dc5-49da-8646-d4a00a1a2cef.png">
> 
> this is an edge case where the content isn't fittable on either of the two table sizes fixed by design.

this is addressed here https://github.com/holdex/holdex-venture-studio/pull/517

cc @georgeciubotaru @zolotokrylin

**Comment by zolotokrylin** [comment]
Are you going to charge us more for introducing and fixing your own bug? @surajsharma ?

**Comment by surajsharma** [comment]
> Are you going to charge us more for introducing and fixing your own bug? @surajsharma ?

😋🔫

**Comment by zolotokrylin** [comment]
@georgeciubotaru please resolve this one

**Comment by surajsharma** [comment]
#517 was supposed to be a bugfix thats still not merged, pls lets have rational levels of scrutiny in the absence of an explicit style guide @zolotokrylin @georgeciubotaru thanks!
