### ISSUE TITLE
Problem: feed card has confusing name and wrong HTML semantics

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/holdex-venture-studio#580]
Problem: feed card component has the wrong HTML semantics / SEO
```[tasklist]
### Tasks
- [x] fix semantics (see how it is done on Portfolio page)
- [x] rename component, because it is called as Jobs item, but Guides are not jobs
- [ ] Modify resource feed item heading - https://github.com/holdex/holdex-venture-studio/issues/580#issuecomment-1933590801
```

sub of https://github.com/holdex/marketing/issues/18

**Comment by angelicawill** [comment]
@zolotokrylin can you elaborate on `fix semantics (see how it is done on Portfolio page)`?

**Comment by zolotokrylin** [comment]
Discussed on the call.

**Comment by angelicawill** [comment]
Log; discussed on a call

- refactor anchor tag in feed item 
- chahnge div to article tag for feed item

**Comment by zolotokrylin** [comment]
@angelicawill within thin issue please fix (both in Figma and on the website): 

Wrong: 
<img width="734" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/b1552082-7a50-4e9d-859b-d38055d0f2be">

Correct: 
<img width="454" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/d5125dfd-2c13-4cf2-9770-4767dee909e8">
